---
name: build-and-publish-protos
on:
  pull_request:
    paths:
      - 'proto/**/*.proto'
jobs:
  build-and-publish-protos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: bufbuild/buf-setup-action@v1.19.0

      - name: Verify that protos build.
        run: buf build

      - id: push-aep-type
        uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: proto/aep-type
          draft: ${{ github.ref_name != 'main'}}

      - id: push-aep-api
        uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          input: proto/aep-type
          draft: ${{ github.ref_name != 'main'}}